Repository Benawi/Doctor_Appointment-Booking_App, pull requests merged in 2023-10, with the labels that each got.

#9 Feature/migrations
  db/migrate/20231014154035_creat_users.rb
  db/migrate/20231014160332_specialization.rb
  db/migrate/20231014160333_create_doctors.rb
  db/migrate/20231014163015_create_appointments.rb
  db/migrate/20231014163343_create_bookings.rb
  db/migrate/20231014163513_add_user_reference_to_booking.rb
  db/schema.rb
Labels: db

#12 Doctor Appointment Booking App- New Milestone
  app/assets/stylesheets/app.css
  app/javascript/application.js
  app/javascript/components/AddDoctor.js
  app/javascript/components/App.js
  app/javascript/components/DeleteDoctor.js
  app/javascript/components/Doctors.js
  app/javascript/components/MainSection.js
  app/javascript/components/MyReservation.js
  app/javascript/components/NabBar.js
  app/javascript/components/ReservseForm.js
  config/database.yml
  db/schema.rb
  package-lock.json
  package.json
  webpack.config.js
  yarn.lock
Labels: enhancement

#13 Doctor Appointment Booking App- New Milestone :Update Database Schema
  db/migrate/20231014154035_creat_users.rb
  db/migrate/20231014160332_specialization.rb
  db/migrate/20231014160333_create_doctors.rb
  db/migrate/20231014163015_create_appointments.rb
  db/migrate/20231014163343_create_bookings.rb
  db/migrate/20231014163513_add_user_reference_to_booking.rb
  db/migrate/20231017135804_create_users.rb
  db/migrate/20231017140032_create_specializations.rb
  db/migrate/20231017140429_create_doctors.rb
  db/migrate/20231017140803_create_reservations.rb
  db/schema.rb
Labels: enhancement

#14 Feature/model
  .eslintrc.json
  Gemfile
  Gemfile.lock
  app/assets/images/logo.ai
  app/assets/images/logo.png
  app/controllers/api/v1/appointments_controller.rb
  app/controllers/api/v1/doctors_controller.rb
  app/models/doctor.rb
  app/models/reservation.rb
  app/models/specialization.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  config/application.rb
  config/cable.yml
  config/database.yml
  config/environments/production.rb
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/routes.rb
  db/seeds.rb
  package-lock.json
  package.json
  spec/swagger_helper.rb
  test/fixtures/doctors.yml
  test/models/doctor_test.rb
  yarn.lock
Labels: enhancement

#15 Feature/controller
  .eslintrc.json
  Gemfile
  Gemfile.lock
  app/assets/images/logo.ai
  app/assets/images/logo.png
  app/controllers/api/v1/appointments_controller.rb
  app/controllers/api/v1/doctors_controller.rb
  app/models/doctor.rb
  app/models/reservation.rb
  app/models/specialization.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  config/application.rb
  config/cable.yml
  config/database.yml
  config/environments/production.rb
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/routes.rb
  db/seeds.rb
  package-lock.json
  package.json
  spec/swagger_helper.rb
  test/fixtures/doctors.yml
  test/models/doctor_test.rb
  yarn.lock
Labels: Controller - API

#16 Feature/setup users
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/users/index.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20231017135804_create_users.rb
  db/migrate/20231017140031_devise_create_users.rb
  db/migrate/20231018111238_add_username_to_users.rb
  db/schema.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: enhancement

#20 Feature/front end
  app/assets/images/doctor-logo.png
  app/assets/images/fb-icon-home.png
  app/assets/images/insta-icon-home.png
  app/assets/images/login.jpg
  app/assets/images/twitter-icon-home.png
  app/assets/stylesheets/add_doctor.css
  app/assets/stylesheets/app.css
  app/assets/stylesheets/delete_doctor.css
  app/assets/stylesheets/detail.css
  app/assets/stylesheets/doctors.css
  app/assets/stylesheets/main.css
  app/controllers/api/v1/doctors_controller.rb
  app/controllers/api/v1/reservations_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/javascript/application.js
  app/javascript/components/AddDoctor.js
  app/javascript/components/App.js
  app/javascript/components/DeleteDoctor.js
  app/javascript/components/DoctorDetails.js
  app/javascript/components/Doctors.js
  app/javascript/components/Header.js
  app/javascript/components/MyReservation.js
  app/javascript/components/NabBar.js
  app/javascript/components/ReservseForm.js
  app/javascript/components/SingleDoctor.js
  app/javascript/redux/configureStore.js
  app/javascript/redux/doctors/doctorsSlice.js
  app/javascript/redux/reservations/reservationsSlice.js
  config/database.yml
  config/routes.rb
  db/seeds.rb
  package-lock.json
  package.json
  webpack.config.js
  yarn.lock
Labels: enhancement

#21 Feature/responsive page
  app/assets/stylesheets/add_doctor.css
  app/assets/stylesheets/delete_doctor.css
  app/assets/stylesheets/doctors.css
  app/assets/stylesheets/main.css
  app/assets/stylesheets/responsive.css
  app/assets/stylesheets/table.css
  app/controllers/api/v1/doctors_controller.rb
  app/javascript/components/AddDoctor.js
  app/javascript/components/App.js
  app/javascript/components/DeleteDoctor.js
  app/javascript/components/Doctors.js
  app/javascript/components/NabBar.js
  app/javascript/components/SingleDoctor.js
  app/javascript/redux/doctors/doctorsSlice.js
  app/javascript/redux/reservations/reservationsSlice.js
  app/javascript/redux/specializations/specializationsSlice.js
  config/routes.rb
  db/migrate/20231022163842_add_uuid_todoctors.rb
  db/schema.rb
  db/seeds.rb
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#23 Feature/bug fix
  Gemfile
  Gemfile.lock
  app/javascript/components/AddDoctor.js
  app/javascript/components/App.js
  app/javascript/components/DeleteDoctor.js
  app/javascript/components/DoctorDetails.js
  app/javascript/components/Doctors.js
  app/javascript/components/Header.js
  app/javascript/components/Logout.js
  app/javascript/components/MainSection.js
  app/javascript/components/MyReservation.js
  app/javascript/components/NabBar.js
  app/javascript/components/ReservseForm.js
  app/javascript/components/SingleDoctor.js
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  config/database.yml
  jest.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement
